application: roseboticsweb
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  GCB_PRODUCT_VERSION: '1.6.0'
  GCB_APPSTATS_ENABLED: false
  GCB_COURSES_CONFIG: 'course:/cs1:/courses/cs1, course:/smartproductdesign:/courses/smartproductdesign, course:/android:/courses/android, course:/web:/courses/web, course:/ios:/courses/ios, course:/misc:/courses/misc, course:/me430:/courses/me430'

# Turned off warmup requests for development.  For more details visit:
# https://developers.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Warmup_requests
#inbound_services:
#- warmup

builtins:
- remote_api: on
- deferred: on

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static/
  static_dir: static
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always
- url: /cron/.*
  script: main.app
  login: admin
  secure: always
- url: /mapreduce/worker/.*
  script: main.app
  login: admin
  secure: always
- url: /.*
  script: main.app
