application: roseboticswebdemo
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  GCB_PRODUCT_VERSION: '1.7.0'
  GCB_APPSTATS_ENABLED: false
  GCB_REGISTERED_MODULES:
    modules.activity_tag.activity_tag
    modules.admin.admin
    modules.announcements.announcements
    modules.assessment_tags.questions
    modules.certificate.certificate
    modules.core_tags.core_tags
    modules.course_explorer.course_explorer
    modules.courses.courses
    modules.data_source_providers.data_source_providers
    modules.dashboard.dashboard
    modules.i18n_dashboard.i18n_dashboard
    modules.invitation.invitation
    modules.manual_progress.manual_progress
    modules.mapreduce.mapreduce_module
    modules.math.math
    modules.notifications.notifications
    modules.oeditor.oeditor
    modules.review.review
    modules.search.search
    modules.unsubscribe.unsubscribe
    modules.upload.upload
    modules.oauth2.oauth2=disabled
  GCB_COURSES_CONFIG: >
                        course:/cs1:/courses/cs1, 
                        course:/smartproductdesign:/courses/smartproductdesign,
                        course:/android-intro:/courses/android-intro, 
                        course:/android-ui:/courses/android-ui, 
                        course:/android-storage:/courses/android-storage, 
                        course:/android-cloud-endpoints:/courses/android-cloud-endpoints, 
                        course:/android:/courses/android, 
                        course:/web-appengine:/courses/web-appengine, 
                        course:/web-css:/courses/web-css, 
                        course:/web-js:/courses/web-js, 
                        course:/ios:/courses/ios, 
                        course:/misc:/courses/misc, 
                        course:/me430:/courses/me430

includes:
- custom.yaml

inbound_services:
- warmup

builtins:
- remote_api: on
- deferred: on

libraries:
- name: jinja2
  version: "2.6"
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static/
  static_dir: static
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always
- url: /cron/.*
  script: main.app
  login: admin
  secure: always
- url: /mapreduce/worker/.*
  script: main.app
  login: admin
  secure: always
- url: /.*
  script: main.app
